#!/bin/bash
stamp=`date "+%d/%m/%y %H:%M:%S"`" $1"
echo "$stamp runScenarios"
echo "$stamp runScenarios" >> log
runs=3;
for ((x=1;x<=$runs;x++)) ; do
	for i in $(ls $1*.map.scen*);
	do
			echo "$i"
			./bin/hog -scenario $i -nogui $2 >> log
			if [ "$?" -ne "0" ]
			then
				err="Failed while executing: ./bin/hog -scenario $i -nogui $2";
				echo $err >> log
				echo $err
				exit 1
			fi
	done
done
