#!/bin/bash
stamp=`date "+%d/%m/%y %H:%M:%S"`" $1"
echo "$stamp runScenarios"
echo "$stamp runScenarios" >> log

runs=
if [ -n "$3" ]
then
	runs=$3
else
	runs=1
fi

for ((x=1;x<=$runs;x++)) ; do
	for i in $(ls $1);
	do
			echo "$i"
			./bin/hog -scenario $i -nogui $2 >> log
			if [ "$?" -ne "0" ]
			then
				err="Failed while executing: ./bin/hog -scenario $i -nogui $2";
				echo $err >> log
				echo $err
				exit 1
			fi
	done
done
