all:
	make -f hog.mk
	make -f entry.mk

.PHONY: fast
fast:
	make -f hog.mk fast
	make -f entry.mk fast

.PHONY: dev
dev:
	make -f hog.mk dev
	make -f entry.mk dev

clean:
	make -f hog.mk clean
	make -f entry.mk clean

