#!/bin/bash
rm results_*
rm -rf ad/
mkdir ad
./runScenarios experiments/scenarios/adaptive-depth/ "-abs flat"
./runScenarios experiments/scenarios/adaptive-depth/ "-abs hpa"
mv results* ad/
./runScenarios experiments/scenarios/adaptive-depth/ "-abs flatjump"
mv results_FlexibleAStar ad/results_FlexibleAStarJump

rm -rf bgm/
mkdir bgm
./runScenarios experiments/scenarios/movingai/bgmaps/ "-abs flat"
./runScenarios experiments/scenarios/movingai/bgmaps/ "-abs hpa"
mv results* bgm/
./runScenarios experiments/scenarios/movingai/bgmaps/ "-abs flatjump"
mv results_FlexibleAStar bgm/results_FlexibleAStarJump

rm -rf rooms/
mkdir rooms
./runScenarios experiments/scenarios/rooms/ "-abs flat"
./runScenarios experiments/scenarios/rooms/ "-abs hpa"
mv results* rooms/
./runScenarios experiments/scenarios/rooms/ "-abs flatjump"
mv results_FlexibleAStar rooms/results_FlexibleAStarJump

rm -rf dao
mkdir dao
./runScenarios experiments/scenarios/movingai/dao/ "-abs flat"
./runScenarios experiments/scenarios/movingai/dao/ "-abs hpa"
mv results* dao/
./runScenarios experiments/scenarios/movingai/dao/ "-abs flatjump"
mv results_FlexibleAStar dao/results_FlexibleAStarJump
