all:
	make -f entry_jps.mk
	make -f entry_jps_plus.mk

.PHONY: fast
fast:
	make -f entry_jps.mk fast
	make -f entry_jps_plus.mk fast

.PHONY: dev
dev:
	make -f entry_jps.mk dev
	make -f entry_jps_plus.mk dev

clean:
	make -f entry_jps.mk clean
	make -f entry_jps_plus.mk clean

